### ISSUE TITLE
Where can I get the *.semantic files?

### ISSUE THREAD

**Issue by AlbertChenJX** [PRBonn/leaf-plant-instance-segmentation#3]
Where can I download the dataset and the corresponding *.semantic files?
Like this:
![2023-09-12_083349](https://github.com/PRBonn/leaf-plant-instance-segmentation/assets/102857436/609375e8-830c-482f-bfa7-9294cdb8c9c5)

**Comment by JaWeyl** [comment]
The dataset we used in our paper is not publicly available since it was created together with an industrial company.
We just provide a sample to show the overall pipeline.

However, the [PhenoBench dataset](https://www.phenobench.org/) might be a good alternative.
